// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSa3pooOWOld4Cejh626rpnYeH8sKo1kk',
    appId: '1:172940963011:web:bc185ebfcad18928b3c676',
    messagingSenderId: '172940963011',
    projectId: 'prayojana-stage',
    authDomain: 'prayojana-stage.firebaseapp.com',
    storageBucket: 'prayojana-stage.appspot.com',
    measurementId: 'G-4L83N7LS3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQKEmgNP-pE8epBsNcc4EOdrfX1u9Cv4',
    appId: '1:172940963011:android:044af85c172219b4b3c676',
    messagingSenderId: '172940963011',
    projectId: 'prayojana-stage',
    storageBucket: 'prayojana-stage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwh4ZKA4IAQGtpqf0xFlEJuoielsKcrEI',
    appId: '1:172940963011:ios:1ad19ff9d215f1eeb3c676',
    messagingSenderId: '172940963011',
    projectId: 'prayojana-stage',
    storageBucket: 'prayojana-stage.appspot.com',
    iosBundleId: 'com.example.prayojanaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwh4ZKA4IAQGtpqf0xFlEJuoielsKcrEI',
    appId: '1:172940963011:ios:1ad19ff9d215f1eeb3c676',
    messagingSenderId: '172940963011',
    projectId: 'prayojana-stage',
    storageBucket: 'prayojana-stage.appspot.com',
    iosBundleId: 'com.example.prayojanaNew',
  );
}
