// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7JWcZSqvOkZ_4XwtLVscE2rwYTEXLqRs',
    appId: '1:759450326852:web:6754d1027917657b35e911',
    messagingSenderId: '759450326852',
    projectId: 'prayojana-fa07b',
    authDomain: 'prayojana-fa07b.firebaseapp.com',
    storageBucket: 'prayojana-fa07b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22cas1-X_iMXRhmCVeCstORQaEN9Dh2E',
    appId: '1:759450326852:android:d71fc4732a1713b335e911',
    messagingSenderId: '759450326852',
    projectId: 'prayojana-fa07b',
    storageBucket: 'prayojana-fa07b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKU6VXrxtsJtW2v3C1uUYt30aIBECr120',
    appId: '1:759450326852:ios:258fac6b81a72b5f35e911',
    messagingSenderId: '759450326852',
    projectId: 'prayojana-fa07b',
    storageBucket: 'prayojana-fa07b.appspot.com',
    androidClientId: '759450326852-2mea2vjick560hmm63gfj9tjat53jlm7.apps.googleusercontent.com',
    iosClientId: '759450326852-q6qaefucbrnk0gveh1g4cfd74sjv556r.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayojanaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKU6VXrxtsJtW2v3C1uUYt30aIBECr120',
    appId: '1:759450326852:ios:258fac6b81a72b5f35e911',
    messagingSenderId: '759450326852',
    projectId: 'prayojana-fa07b',
    storageBucket: 'prayojana-fa07b.appspot.com',
    androidClientId: '759450326852-2mea2vjick560hmm63gfj9tjat53jlm7.apps.googleusercontent.com',
    iosClientId: '759450326852-q6qaefucbrnk0gveh1g4cfd74sjv556r.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayojanaNew',
  );
}
